name = "WebTerminal"
uuid = "072d345f-df84-4301-a21d-dc9ae24b65cd"
authors = ["Jamie Mair <JamieMair@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
julia = "1.6"